### ISSUE TITLE
Skannerid

### ISSUE THREAD

**Issue by gristo23** [TLUHK-RIF23/Gristo-Joesaar#1]
https://github.com/TLUHK-RIF23/Gristo-Joesaar/blob/main/Skannerid/Skannerite_t%C3%BC%C3%BCbid.md

**Comment by mrtrvl** [comment]
Tõsta see sisu, mis ilmselt Google Drives on, oma repositooriumisse eraldi faili alla.

**Comment by gristo23** [comment]
Nüüd peaks korras olema

**Comment by mrtrvl** [comment]
Kui nüüd korra selle dokumendi lahti võtad ja selle üle vaatad, siis kas tunudb, et kõik on korras? 😃

**Comment by gristo23** [comment]
https://github.com/gristo23/Gristo-Joesaar/blob/main/Skannerid/Skannerid.md

Kas nüüd võiks olla ? :)

**Comment by mrtrvl** [comment]
See link Sul tuleb endal lahti praegu?

**Comment by gristo23** [comment]
Mul avaneb selline dokument

![Capture _Github](https://github.com/TLUHK-RIF23/Gristo-Joesaar/assets/143442522/10430fbf-59ac-4049-8723-f626cacc4532)

**Comment by mrtrvl** [comment]
Mina näen sellist:
![image](https://github.com/TLUHK-RIF23/Gristo-Joesaar/assets/26817366/948b718f-51c9-4948-979f-3be70c741237)

Ilmselt sellepärast, et Sul on see dokument oma privaatses repositooriumis, mitte `RIF-23` organisatsiooni all olevas omanimelises repositooriumis.
